version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-container
    hostname: kafka_broker
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_broker:9092,PLAINTEXT_HOST://kafka_broker:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  service-bdd:
    image: mongo
    container_name: service-bdd-container
    hostname: service-bdd
    restart: always
    ports:
      - '27017:27017'

  service-registry:
    container_name: service-registry-container
    hostname: registry
    build: ./registry
    ports:
      - '8761:8761'

  service-entreprise:
    build: ./microservice-entreprise
    container_name: service-entreprise-container
    hostname: entreprise
    depends_on:
      - service-bdd
      - service-registry
      - kafka
    environment:
      - MONGO_DB_HOST=service-bdd
      - MONGO_DB_PORT=27017
      - MONGO_DB_NAME=Entreprise
      - EUREKA_URL=http://registry:8761/eureka/
      - KAFKA_BROKER=kafka_broker:29092
    ports:
      - '8181:8181'

  service-todolist:
    build: ./microservice-todolist
    container_name: service-todolist-container
    hostname: todolist
    depends_on:
      - service-entreprise
    environment:
      - MONGO_DB_HOST=service-bdd
      - MONGO_DB_PORT=27017
      - MONGO_DB_NAME=ToDoList
      - EUREKA_URL=http://registry:8761/eureka/
      - KAFKA_BROKER=kafka_broker:29092
    ports:
      - '8282:8282'

