apiVersion: v1
kind: Service
metadata:
  name: registry-service
spec:
  ports:
    - name: http
      targetPort: 8761
      port: 8761
  type: ClusterIP
  selector:
    app: registry
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  ports:
    - name: http
      targetPort: 27017
      port: 27017
  type: ClusterIP
  selector:
    app: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: entreprise-service
spec:
  ports:
    - name: http
      targetPort: 8181
      port: 8181
  selector:
    app: entreprise
---
apiVersion: v1
kind: Service
metadata:
  name: to-do-service
spec:
  ports:
    - name: http
      targetPort: 8282
      port: 8282
  selector:
    app: to-do
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  ports:
    - name: http
      targetPort: 2181
      port: 2181
  selector:
    app: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  ports:
    - name: http
      targetPort: 29092
      port: 29092
  selector:
    app: kafka
